import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/figma-variables">Figma Variables</Link>&nbsp;|&nbsp;
          <Link href="/token-studio">Token Studio</Link>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
