import type { Metadata } from "next"
import Link from "next/link"
import { Inter } from "next/font/google"

import { AntdRegistry } from '@ant-design/nextjs-registry'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <nav>
            <Link href="/figma-variables">Figma Variables</Link>&nbsp;|&nbsp;
            <Link href="/token-studio">Token Studio</Link>&nbsp;|&nbsp;
            <Link href="/design-system">Design System</Link>
          </nav>
          <main>
            {children}
          </main>
        </AntdRegistry>
      </body>
    </html>
  );
}
